package org.debugroom.sample.spring.jpa.domain.entity;
// Generated 2016/10/03 20:01:52 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AffiliationId generated by hbm2java
 */
@Embeddable
public class AffiliationId implements java.io.Serializable {

	private String groupId;
	private String userId;

	public AffiliationId() {
	}

	public AffiliationId(String groupId, String userId) {
		this.groupId = groupId;
		this.userId = userId;
	}

	@Column(name = "group_id", nullable = false, length = 10)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "user_id", nullable = false, length = 8)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AffiliationId))
			return false;
		AffiliationId castOther = (AffiliationId) other;

		return ((this.getGroupId() == castOther.getGroupId()) || (this.getGroupId() != null
				&& castOther.getGroupId() != null && this.getGroupId().equals(castOther.getGroupId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getGroupId() == null ? 0 : this.getGroupId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
