package org.debugroom.sample.spring.jpa.domain.entity;
// Generated 2016/10/03 20:01:52 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Affiliation generated by hbm2java
 */
@Entity
@Table(name = "affiliation", schema = "public")
public class Affiliation implements java.io.Serializable {

	private AffiliationId id;
	private Group grp;
	private User usr;
	private Integer ver;
	private Date lastUpdatedDate;

	public Affiliation() {
	}

	public Affiliation(AffiliationId id, Group grp, User usr) {
		this.id = id;
		this.grp = grp;
		this.usr = usr;
	}

	public Affiliation(AffiliationId id, Group grp, User usr, Integer ver, Date lastUpdatedDate) {
		this.id = id;
		this.grp = grp;
		this.usr = usr;
		this.ver = ver;
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "groupId", column = @Column(name = "group_id", nullable = false, length = 10) ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 8) ) })
	public AffiliationId getId() {
		return this.id;
	}

	public void setId(AffiliationId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id", nullable = false, insertable = false, updatable = false)
	public Group getGrp() {
		return this.grp;
	}

	public void setGrp(Group grp) {
		this.grp = grp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUsr() {
		return this.usr;
	}

	public void setUsr(User usr) {
		this.usr = usr;
	}

	@Column(name = "ver")
	public Integer getVer() {
		return this.ver;
	}

	public void setVer(Integer ver) {
		this.ver = ver;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_date", length = 29)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

}
