package org.debugroom.sample.spring.jpa.domain.entity;
// Generated 2016/10/03 20:01:52 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmailId generated by hbm2java
 */
@Embeddable
public class EmailId implements java.io.Serializable {

	private String userId;
	private String emailId;

	public EmailId() {
	}

	public EmailId(String userId, String emailId) {
		this.userId = userId;
		this.emailId = emailId;
	}

	@Column(name = "user_id", nullable = false, length = 8)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "email_id", nullable = false)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmailId))
			return false;
		EmailId castOther = (EmailId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getEmailId() == castOther.getEmailId()) || (this.getEmailId() != null
						&& castOther.getEmailId() != null && this.getEmailId().equals(castOther.getEmailId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getEmailId() == null ? 0 : this.getEmailId().hashCode());
		return result;
	}

}
