package org.debugroom.sample.spring.jpa.domain.entity;
// Generated 2016/10/03 20:01:52 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name = "email", schema = "public")
public class Email implements java.io.Serializable {

	private EmailId id;
	private User usr;
	private String email;
	private Integer ver;
	private Date lastUpdatedDate;

	public Email() {
	}

	public Email(EmailId id, User usr) {
		this.id = id;
		this.usr = usr;
	}

	public Email(EmailId id, User usr, String email, Integer ver, Date lastUpdatedDate) {
		this.id = id;
		this.usr = usr;
		this.email = email;
		this.ver = ver;
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 8) ),
			@AttributeOverride(name = "emailId", column = @Column(name = "email_id", nullable = false) ) })
	public EmailId getId() {
		return this.id;
	}

	public void setId(EmailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUsr() {
		return this.usr;
	}

	public void setUsr(User usr) {
		this.usr = usr;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ver")
	public Integer getVer() {
		return this.ver;
	}

	public void setVer(Integer ver) {
		this.ver = ver;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_date", length = 29)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

}
