package org.debugroom.sample.spring.jpa.domain.entity;
// Generated 2016/10/03 20:01:52 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Grp generated by hbm2java
 */
@Entity
@Table(name = "grp", schema = "public")
public class Group implements java.io.Serializable {

	private String groupId;
	private String groupName;
	private Integer ver;
	private Date lastUpdatedDate;
	private Set<Affiliation> affiliations = new HashSet<Affiliation>(0);

	public Group() {
	}

	public Group(String groupId) {
		this.groupId = groupId;
	}

	public Group(String groupId, String groupName, Integer ver, Date lastUpdatedDate, Set<Affiliation> affiliations) {
		this.groupId = groupId;
		this.groupName = groupName;
		this.ver = ver;
		this.lastUpdatedDate = lastUpdatedDate;
		this.affiliations = affiliations;
	}

	@Id

	@Column(name = "group_id", unique = true, nullable = false, length = 10)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "group_name", length = 50)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "ver")
	public Integer getVer() {
		return this.ver;
	}

	public void setVer(Integer ver) {
		this.ver = ver;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated_date", length = 29)
	public Date getLastUpdatedDate() {
		return this.lastUpdatedDate;
	}

	public void setLastUpdatedDate(Date lastUpdatedDate) {
		this.lastUpdatedDate = lastUpdatedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grp")
	public Set<Affiliation> getAffiliations() {
		return this.affiliations;
	}

	public void setAffiliations(Set<Affiliation> affiliations) {
		this.affiliations = affiliations;
	}

}
