
/* Drop Tables */

DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS PHONE;
DROP TABLE IF EXISTS EMAIL;
DROP TABLE IF EXISTS CREDENTIAL;
DROP TABLE IF EXISTS USR;
DROP TABLE IF EXISTS COMPANY;




/* Create Tables */

CREATE TABLE ADDRESS
(
	COMPANY_ID char(10) NOT NULL,
	USER_ID char(8) NOT NULL,
	ADDRESS_NO int NOT NULL,
	POST_CD char(7) NOT NULL,
	ADDRESS varchar(255),
	ADDRESS_DETAIL varchar(255),
	PRIMARY KEY (COMPANY_ID, USER_ID, ADDRESS_NO),
	UNIQUE (COMPANY_ID, USER_ID, ADDRESS_NO)
) WITHOUT OIDS;


CREATE TABLE COMPANY
(
	COMPANY_ID char(10) NOT NULL,
	COMPANY_NAME varchar(255),
	PRIMARY KEY (COMPANY_ID)
) WITHOUT OIDS;


CREATE TABLE CREDENTIAL
(
	COMPANY_ID char(10) NOT NULL,
	USER_ID char(8) NOT NULL,
	CREDENTIAL_NO int NOT NULL,
	CREDENTIAL_TYPE char(4) NOT NULL,
	CREDENTIAL_KEY varchar(255),
	KEY_EXPIRED_DATE timestamp,
	ACCESS_TOKEN varchar(512),
	TOKEN_EXPIRED_DATE timestamp with time zone,
	PRIMARY KEY (COMPANY_ID, USER_ID, CREDENTIAL_NO),
	UNIQUE (COMPANY_ID, USER_ID, CREDENTIAL_NO)
) WITHOUT OIDS;


CREATE TABLE EMAIL
(
	COMPANY_ID char(10) NOT NULL,
	USER_ID char(8) NOT NULL,
	EMAIL_NO int NOT NULL,
	EMAIL varchar(255),
	PRIMARY KEY (COMPANY_ID, USER_ID, EMAIL_NO),
	UNIQUE (COMPANY_ID, USER_ID, EMAIL_NO)
) WITHOUT OIDS;


CREATE TABLE PHONE
(
	COMPANY_ID char(10) NOT NULL,
	USER_ID char(8) NOT NULL,
	PHONE_NO int NOT NULL,
	PHONE_NUMBER char(11),
	RELATED_ADDRESS_NO int,
	PRIMARY KEY (COMPANY_ID, USER_ID, PHONE_NO),
	UNIQUE (COMPANY_ID, USER_ID, PHONE_NO)
) WITHOUT OIDS;


CREATE TABLE USR
(
	COMPANY_ID char(10) NOT NULL,
	USER_ID char(8) NOT NULL,
	USER_NAME varchar(255),
	LOGIN_ID varchar(32) NOT NULL UNIQUE,
	BIRTHDAY char(8),
	AUTHORITY_LEVEL int NOT NULL,
	IS_LOGIN boolean NOT NULL,
	PRIMARY KEY (COMPANY_ID, USER_ID),
	UNIQUE (COMPANY_ID, USER_ID)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE USR
	ADD FOREIGN KEY (COMPANY_ID)
	REFERENCES COMPANY (COMPANY_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ADDRESS
	ADD FOREIGN KEY (COMPANY_ID, USER_ID)
	REFERENCES USR (COMPANY_ID, USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PHONE
	ADD FOREIGN KEY (COMPANY_ID, USER_ID)
	REFERENCES USR (COMPANY_ID, USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE EMAIL
	ADD FOREIGN KEY (COMPANY_ID, USER_ID)
	REFERENCES USR (COMPANY_ID, USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CREDENTIAL
	ADD FOREIGN KEY (COMPANY_ID, USER_ID)
	REFERENCES USR (COMPANY_ID, USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

