GRANT USAGE ON SCHEMA public TO app;
GRANT SELECT, UPDATE, INSERT, DELETE ON COMPANY TO app;
GRANT SELECT, UPDATE, INSERT, DELETE ON USR TO app;
GRANT SELECT, UPDATE, INSERT, DELETE ON ADDRESS TO app;
GRANT SELECT, UPDATE, INSERT, DELETE ON CREDENTIAL TO app;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMAIL TO app;
GRANT SELECT, UPDATE, INSERT, DELETE ON PHONE TO app;
