package org.debugroom.sample.jbatch.domain.model.entity;
// Generated 2016/10/02 8:14:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "address", schema = "public")
public class Address implements java.io.Serializable {

	private AddressId id;
	private Usr usr;
	private String postCd;
	private String address;
	private String addressDetail;

	public Address() {
	}

	public Address(AddressId id, Usr usr, String postCd) {
		this.id = id;
		this.usr = usr;
		this.postCd = postCd;
	}

	public Address(AddressId id, Usr usr, String postCd, String address, String addressDetail) {
		this.id = id;
		this.usr = usr;
		this.postCd = postCd;
		this.address = address;
		this.addressDetail = addressDetail;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "companyId", column = @Column(name = "company_id", nullable = false, length = 10) ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 8) ),
			@AttributeOverride(name = "addressNo", column = @Column(name = "address_no", nullable = false) ) })
	public AddressId getId() {
		return this.id;
	}

	public void setId(AddressId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "company_id", referencedColumnName = "company_id", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "user_id", referencedColumnName = "user_id", nullable = false, insertable = false, updatable = false) })
	public Usr getUsr() {
		return this.usr;
	}

	public void setUsr(Usr usr) {
		this.usr = usr;
	}

	@Column(name = "post_cd", nullable = false, length = 7)
	public String getPostCd() {
		return this.postCd;
	}

	public void setPostCd(String postCd) {
		this.postCd = postCd;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "address_detail")
	public String getAddressDetail() {
		return this.addressDetail;
	}

	public void setAddressDetail(String addressDetail) {
		this.addressDetail = addressDetail;
	}

}
