package org.debugroom.sample.jbatch.domain.model.entity;
// Generated 2016/10/02 8:14:26 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Credential generated by hbm2java
 */
@Entity
@Table(name = "credential", schema = "public")
public class Credential implements java.io.Serializable {

	private CredentialId id;
	private Usr usr;
	private String credentialType;
	private String credentialKey;
	private Date keyExpiredDate;
	private String accessToken;
	private Date tokenExpiredDate;

	public Credential() {
	}

	public Credential(CredentialId id, Usr usr, String credentialType) {
		this.id = id;
		this.usr = usr;
		this.credentialType = credentialType;
	}

	public Credential(CredentialId id, Usr usr, String credentialType, String credentialKey, Date keyExpiredDate,
			String accessToken, Date tokenExpiredDate) {
		this.id = id;
		this.usr = usr;
		this.credentialType = credentialType;
		this.credentialKey = credentialKey;
		this.keyExpiredDate = keyExpiredDate;
		this.accessToken = accessToken;
		this.tokenExpiredDate = tokenExpiredDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "companyId", column = @Column(name = "company_id", nullable = false, length = 10) ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 8) ),
			@AttributeOverride(name = "credentialNo", column = @Column(name = "credential_no", nullable = false) ) })
	public CredentialId getId() {
		return this.id;
	}

	public void setId(CredentialId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "company_id", referencedColumnName = "company_id", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "user_id", referencedColumnName = "user_id", nullable = false, insertable = false, updatable = false) })
	public Usr getUsr() {
		return this.usr;
	}

	public void setUsr(Usr usr) {
		this.usr = usr;
	}

	@Column(name = "credential_type", nullable = false, length = 4)
	public String getCredentialType() {
		return this.credentialType;
	}

	public void setCredentialType(String credentialType) {
		this.credentialType = credentialType;
	}

	@Column(name = "credential_key")
	public String getCredentialKey() {
		return this.credentialKey;
	}

	public void setCredentialKey(String credentialKey) {
		this.credentialKey = credentialKey;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "key_expired_date", length = 29)
	public Date getKeyExpiredDate() {
		return this.keyExpiredDate;
	}

	public void setKeyExpiredDate(Date keyExpiredDate) {
		this.keyExpiredDate = keyExpiredDate;
	}

	@Column(name = "access_token", length = 512)
	public String getAccessToken() {
		return this.accessToken;
	}

	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "token_expired_date", length = 35)
	public Date getTokenExpiredDate() {
		return this.tokenExpiredDate;
	}

	public void setTokenExpiredDate(Date tokenExpiredDate) {
		this.tokenExpiredDate = tokenExpiredDate;
	}

}
