package org.debugroom.sample.jbatch.domain.model.entity;
// Generated 2016/10/02 8:14:26 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmailId generated by hbm2java
 */
@Embeddable
public class EmailId implements java.io.Serializable {

	private String companyId;
	private String userId;
	private int emailNo;

	public EmailId() {
	}

	public EmailId(String companyId, String userId, int emailNo) {
		this.companyId = companyId;
		this.userId = userId;
		this.emailNo = emailNo;
	}

	@Column(name = "company_id", nullable = false, length = 10)
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "user_id", nullable = false, length = 8)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "email_no", nullable = false)
	public int getEmailNo() {
		return this.emailNo;
	}

	public void setEmailNo(int emailNo) {
		this.emailNo = emailNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmailId))
			return false;
		EmailId castOther = (EmailId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null
				&& castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& (this.getEmailNo() == castOther.getEmailNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + this.getEmailNo();
		return result;
	}

}
