package org.debugroom.sample.spring.boot.entity;
// Generated 2016/09/30 11:02:30 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AddressId generated by hbm2java
 */
@Embeddable
public class AddressId implements java.io.Serializable {

	private String companyId;
	private String userId;
	private int addressNo;

	public AddressId() {
	}

	public AddressId(String companyId, String userId, int addressNo) {
		this.companyId = companyId;
		this.userId = userId;
		this.addressNo = addressNo;
	}

	@Column(name = "company_id", nullable = false, length = 10)
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "user_id", nullable = false, length = 8)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "address_no", nullable = false)
	public int getAddressNo() {
		return this.addressNo;
	}

	public void setAddressNo(int addressNo) {
		this.addressNo = addressNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AddressId))
			return false;
		AddressId castOther = (AddressId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null
				&& castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& (this.getAddressNo() == castOther.getAddressNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + this.getAddressNo();
		return result;
	}

}
