package org.debugroom.sample.spring.boot.entity;
// Generated 2016/09/30 11:02:30 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "company", schema = "public")
public class Company implements java.io.Serializable {

	private String companyId;
	private String companyName;
	private Set<Usr> usrs = new HashSet<Usr>(0);

	public Company() {
	}

	public Company(String companyId) {
		this.companyId = companyId;
	}

	public Company(String companyId, String companyName, Set<Usr> usrs) {
		this.companyId = companyId;
		this.companyName = companyName;
		this.usrs = usrs;
	}

	@Id

	@Column(name = "company_id", unique = true, nullable = false, length = 10)
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "company_name")
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "company")
	public Set<Usr> getUsrs() {
		return this.usrs;
	}

	public void setUsrs(Set<Usr> usrs) {
		this.usrs = usrs;
	}

}
