package org.debugroom.sample.spring.boot.entity;
// Generated 2016/09/30 11:02:30 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Email generated by hbm2java
 */
@Entity
@Table(name = "email", schema = "public")
public class Email implements java.io.Serializable {

	private EmailId id;
	private Usr usr;
	private String email;

	public Email() {
	}

	public Email(EmailId id, Usr usr) {
		this.id = id;
		this.usr = usr;
	}

	public Email(EmailId id, Usr usr, String email) {
		this.id = id;
		this.usr = usr;
		this.email = email;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "companyId", column = @Column(name = "company_id", nullable = false, length = 10) ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 8) ),
			@AttributeOverride(name = "emailNo", column = @Column(name = "email_no", nullable = false) ) })
	public EmailId getId() {
		return this.id;
	}

	public void setId(EmailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "company_id", referencedColumnName = "company_id", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "user_id", referencedColumnName = "user_id", nullable = false, insertable = false, updatable = false) })
	public Usr getUsr() {
		return this.usr;
	}

	public void setUsr(Usr usr) {
		this.usr = usr;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
