package org.debugroom.sample.spring.boot.entity;
// Generated 2016/09/30 11:02:30 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phone generated by hbm2java
 */
@Entity
@Table(name = "phone", schema = "public")
public class Phone implements java.io.Serializable {

	private PhoneId id;
	private Usr usr;
	private String phoneNumber;
	private Integer relatedAddressNo;

	public Phone() {
	}

	public Phone(PhoneId id, Usr usr) {
		this.id = id;
		this.usr = usr;
	}

	public Phone(PhoneId id, Usr usr, String phoneNumber, Integer relatedAddressNo) {
		this.id = id;
		this.usr = usr;
		this.phoneNumber = phoneNumber;
		this.relatedAddressNo = relatedAddressNo;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "companyId", column = @Column(name = "company_id", nullable = false, length = 10) ),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false, length = 8) ),
			@AttributeOverride(name = "phoneNo", column = @Column(name = "phone_no", nullable = false) ) })
	public PhoneId getId() {
		return this.id;
	}

	public void setId(PhoneId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "company_id", referencedColumnName = "company_id", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "user_id", referencedColumnName = "user_id", nullable = false, insertable = false, updatable = false) })
	public Usr getUsr() {
		return this.usr;
	}

	public void setUsr(Usr usr) {
		this.usr = usr;
	}

	@Column(name = "phone_number", length = 11)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "related_address_no")
	public Integer getRelatedAddressNo() {
		return this.relatedAddressNo;
	}

	public void setRelatedAddressNo(Integer relatedAddressNo) {
		this.relatedAddressNo = relatedAddressNo;
	}

}
