package org.debugroom.sample.spring.boot.entity;
// Generated 2016/09/30 11:02:30 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsrId generated by hbm2java
 */
@Embeddable
public class UsrId implements java.io.Serializable {

	private String companyId;
	private String userId;

	public UsrId() {
	}

	public UsrId(String companyId, String userId) {
		this.companyId = companyId;
		this.userId = userId;
	}

	@Column(name = "company_id", nullable = false, length = 10)
	public String getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(String companyId) {
		this.companyId = companyId;
	}

	@Column(name = "user_id", nullable = false, length = 8)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsrId))
			return false;
		UsrId castOther = (UsrId) other;

		return ((this.getCompanyId() == castOther.getCompanyId()) || (this.getCompanyId() != null
				&& castOther.getCompanyId() != null && this.getCompanyId().equals(castOther.getCompanyId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCompanyId() == null ? 0 : this.getCompanyId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
