spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://${dbserver.ipaddress}:${dbserver.port}/sample-app
    username: ${dbserver.app.username}
    password: ${dbserver.app.password}
    driverClassName: org.postgresql.Driver