GRANT USAGE ON SCHEMA public TO APP;
GRANT SELECT, UPDATE, INSERT, DELETE ON COMPANY TO APP;
GRANT SELECT, UPDATE, INSERT, DELETE ON USR TO APP;
GRANT SELECT, UPDATE, INSERT, DELETE ON ADDRESS TO APP;
GRANT SELECT, UPDATE, INSERT, DELETE ON CREDENTIAL TO APP;
GRANT SELECT, UPDATE, INSERT, DELETE ON EMAIL TO APP;
GRANT SELECT, UPDATE, INSERT, DELETE ON PHONE TO APP;