spring:
  profiles:
    active: dev
cloud:
  aws:
    stack:
      auto: false
    credentials:
      instanceProfile: false
      profileName:
    region:
      auto: false
queue:
  endpoint: https://sqs.ap-northeast-1.amazonaws.com/

